apiVersion : apps/v1
kind: Deployment
metadata:
  name: sigpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: sigpipelinesjavascriptdocker 
    spec:
      containers:
        - name: sigpipelinesjavascriptdocker 
          image: domazacr.azurecr.io/sigpipelinesjavascriptdocker
          ports:
          - containerPort: 8080